//! Generated WGSL header for shader/particles patches, effects, and transitions (§6.3).
//!
//! Every shader gets the same input contract as other patch kinds: `time`, `dt`, `frame`,
//! `env` (trigger envelope), `resolution`, `progress` (transitions), params by name,
//! signals by name, and the stream palette. The renderer fills one uniform buffer per
//! patch with [`Layout::write`] (no allocation) and binds:
//!
//! | binding | resource |
//! |---|---|
//! | `@group(0) @binding(0)` | `se: SeInputs` uniforms |
//! | `@group(0) @binding(1)` | `se_sampler` (linear, clamp) |
//! | `@group(0) @binding(2)` | `se_input` — effect input / transition A |
//! | `@group(0) @binding(3)` | `se_input_b` — transition B |
//! | `@group(0) @binding(4)` | `se_particles` storage buffer (particles kind) |
//!
//! Accessors: `p_<param>()`, `s_<signal with dots as underscores>()`, `palette(i)` with
//! `PAL_*` indices, and a full-screen vertex entry `se_vs` producing `SeVsOut { pos, uv }`.

use crate::manifest::Manifest;
use se_proto::ValueType;

/// Signals every shader can read without declaring them.
pub const STANDARD_SIGNALS: &[&str] = &[
    "band.level",
    "band.bass",
    "band.mid",
    "band.high",
    "band.kick",
    "band.snare",
    "band.hat",
    "band.centroid",
    "music.level",
    "music.bass",
    "music.mid",
    "music.high",
    "beat.phase",
    "beat.bpm",
    "mic.level",
    "lfo.slow",
    "lfo.mid",
    "lfo.fast",
    "lfo.beat",
    "lfo.bar",
    "lfo.random",
];

/// Stream palette slots (§16.2).
pub const PALETTE: &[&str] = &["ACCENT", "BACKGROUND", "FOREGROUND", "RED", "YELLOW", "GREEN", "CYAN", "MAGENTA"];

/// Float offsets of the fixed fields in the uniform block.
pub mod off {
    pub const TIME: usize = 0;
    pub const DT: usize = 1;
    /// u32 bits
    pub const FRAME: usize = 2;
    pub const ENV: usize = 3;
    pub const RESOLUTION: usize = 4;
    pub const PROGRESS: usize = 6;
    /// u32 bits
    pub const TRIGGER_COUNT: usize = 7;
    pub const BEAT_PHASE: usize = 8;
    pub const BPM: usize = 9;
    pub const PALETTE: usize = 12;
    pub const PARAMS: usize = 12 + 8 * 4;
}

#[derive(Clone, Debug, PartialEq)]
pub struct Layout {
    /// `(name, type, float offset from the start of the block)`
    pub params: Vec<(String, ValueType, usize)>,
    pub param_rows: usize,
    /// Signal names in slot order.
    pub signals: Vec<String>,
    pub signals_offset: usize,
    pub signal_rows: usize,
    /// Total size in f32s (multiple of 4).
    pub floats: usize,
}

fn mangle(s: &str) -> String {
    s.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect()
}

impl Layout {
    pub fn new(m: &Manifest) -> Layout {
        let slots = m.param_slots();
        let used = slots.iter().map(|(_, p, o)| o + p.slots()).max().unwrap_or(0);
        let param_rows = used.div_ceil(4).max(1);
        let params = slots.iter().map(|(n, p, o)| (n.to_string(), p.value_type(), off::PARAMS + o)).collect();
        let mut signals: Vec<String> = STANDARD_SIGNALS.iter().map(|s| s.to_string()).collect();
        for s in &m.signals {
            if !signals.contains(s) {
                signals.push(s.clone());
            }
        }
        let signals_offset = off::PARAMS + param_rows * 4;
        let signal_rows = signals.len().div_ceil(4).max(1);
        Layout { params, param_rows, signals, signals_offset, signal_rows, floats: signals_offset + signal_rows * 4 }
    }

    pub fn byte_size(&self) -> usize {
        self.floats * 4
    }

    /// The WGSL header to prepend to the patch source.
    pub fn header(&self) -> String {
        let mut s = String::from("// ---- generated by stream-engine; do not edit ----\n");
        s += "struct SeInputs {\n  time: f32,\n  dt: f32,\n  frame: u32,\n  env: f32,\n  resolution: vec2<f32>,\n  progress: f32,\n  trigger_count: u32,\n  beat_phase: f32,\n  bpm: f32,\n  _pad0: f32,\n  _pad1: f32,\n";
        s += &format!("  palette: array<vec4<f32>, {}>,\n", PALETTE.len());
        s += &format!("  params: array<vec4<f32>, {}>,\n", self.param_rows);
        s += &format!("  signals: array<vec4<f32>, {}>,\n}}\n", self.signal_rows);
        s += "@group(0) @binding(0) var<uniform> se: SeInputs;\n@group(0) @binding(1) var se_sampler: sampler;\n@group(0) @binding(2) var se_input: texture_2d<f32>;\n@group(0) @binding(3) var se_input_b: texture_2d<f32>;\n";
        for (i, p) in PALETTE.iter().enumerate() {
            s += &format!("const PAL_{p}: u32 = {i}u;\n");
        }
        s += "fn palette(i: u32) -> vec4<f32> { return se.palette[i]; }\n";
        for (name, ty, o) in &self.params {
            let rel = o - off::PARAMS;
            let (row, col) = (rel / 4, rel % 4);
            let comp = ["x", "y", "z", "w"];
            let body = match ty {
                ValueType::Color | ValueType::Vec4 => format!("vec4<f32> {{ return se.params[{row}]; }}"),
                ValueType::Vec2 => format!("vec2<f32> {{ return se.params[{row}].{}{}; }}", comp[col], comp[col + 1]),
                ValueType::Int | ValueType::Enum => format!("i32 {{ return i32(se.params[{row}].{}); }}", comp[col]),
                ValueType::Bool => format!("bool {{ return se.params[{row}].{} > 0.5; }}", comp[col]),
                _ => format!("f32 {{ return se.params[{row}].{}; }}", comp[col]),
            };
            s += &format!("fn p_{}() -> {body}\n", mangle(name));
        }
        for (i, name) in self.signals.iter().enumerate() {
            let comp = ["x", "y", "z", "w"][i % 4];
            s += &format!("fn s_{}() -> f32 {{ return se.signals[{}].{comp}; }}\n", mangle(name), i / 4);
        }
        s += "struct SeVsOut { @builtin(position) pos: vec4<f32>, @location(0) uv: vec2<f32> };\n";
        s += "@vertex fn se_vs(@builtin(vertex_index) i: u32) -> SeVsOut {\n  let p = vec2<f32>(f32((i << 1u) & 2u), f32(i & 2u));\n  var o: SeVsOut;\n  o.pos = vec4<f32>(p * 2.0 - 1.0, 0.0, 1.0);\n  o.uv = vec2<f32>(p.x, 1.0 - p.y);\n  return o;\n}\n";
        s += "// ---- end of generated header ----\n";
        s
    }

    /// Number of header lines (to map compiler error lines back to the patch source).
    pub fn header_lines(&self) -> usize {
        self.header().lines().count()
    }

    /// Fill a uniform block. `param` returns each param's current value; `signal` each signal.
    #[allow(clippy::too_many_arguments)]
    pub fn write(
        &self,
        buf: &mut [f32],
        time: f32,
        dt: f32,
        frame: u32,
        env: f32,
        resolution: [f32; 2],
        progress: f32,
        trigger_count: u32,
        palette: &[[f32; 4]; 8],
        mut param: impl FnMut(usize, &str) -> [f32; 4],
        mut signal: impl FnMut(usize, &str) -> f32,
    ) {
        debug_assert!(buf.len() >= self.floats);
        buf[off::TIME] = time;
        buf[off::DT] = dt;
        buf[off::FRAME] = f32::from_bits(frame);
        buf[off::ENV] = env;
        buf[off::RESOLUTION] = resolution[0];
        buf[off::RESOLUTION + 1] = resolution[1];
        buf[off::PROGRESS] = progress;
        buf[off::TRIGGER_COUNT] = f32::from_bits(trigger_count);
        for (i, c) in palette.iter().enumerate() {
            buf[off::PALETTE + i * 4..off::PALETTE + i * 4 + 4].copy_from_slice(c);
        }
        for (i, (name, ty, o)) in self.params.iter().enumerate() {
            let v = param(i, name);
            let n = match ty {
                ValueType::Color | ValueType::Vec4 => 4,
                ValueType::Vec2 => 2,
                _ => 1,
            };
            buf[*o..*o + n].copy_from_slice(&v[..n]);
        }
        for (i, name) in self.signals.iter().enumerate() {
            let v = signal(i, name);
            buf[self.signals_offset + i] = v;
            if name == "beat.phase" {
                buf[off::BEAT_PHASE] = v;
            } else if name == "beat.bpm" {
                buf[off::BPM] = v;
            }
        }
    }
}

/// Map a line number in the compiled (header + source) shader back to the patch source.
pub fn source_line(layout: &Layout, compiled_line: usize) -> Option<usize> {
    compiled_line.checked_sub(layout.header_lines())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    fn manifest() -> Manifest {
        Manifest::parse(
            Path::new("/p/patches/aurora"),
            "kind = \"shader\"\nparams.speed = { type = \"float\", default = 1.0 }\nparams.tint = { type = \"color\" }\nparams.count = { type = \"int\" }\nsignals = [\"mixer.16r.meter.ch.1\"]",
        )
        .unwrap()
    }

    #[test]
    fn header_declares_accessors() {
        let l = Layout::new(&manifest());
        let h = l.header();
        assert!(h.contains("fn p_speed() -> f32"));
        assert!(h.contains("fn p_tint() -> vec4<f32>"));
        assert!(h.contains("fn p_count() -> i32"));
        assert!(h.contains("fn s_band_kick() -> f32"));
        assert!(h.contains("fn s_mixer_16r_meter_ch_1() -> f32"));
        assert!(h.contains("@vertex fn se_vs"));
        assert_eq!(l.floats % 4, 0);
    }

    #[test]
    fn write_fills_offsets() {
        let l = Layout::new(&manifest());
        let mut buf = vec![0.0f32; l.floats];
        let pal = [[0.5; 4]; 8];
        l.write(
            &mut buf,
            1.5,
            0.016,
            7,
            0.25,
            [1920.0, 1080.0],
            0.0,
            2,
            &pal,
            |_, n| if n == "tint" { [1.0, 0.0, 0.0, 1.0] } else { [3.0, 0.0, 0.0, 0.0] },
            |_, n| if n == "beat.phase" { 0.75 } else { 0.1 },
        );
        assert_eq!(buf[off::TIME], 1.5);
        assert_eq!(buf[off::FRAME].to_bits(), 7);
        assert_eq!(buf[off::BEAT_PHASE], 0.75);
        let tint = l.params.iter().find(|p| p.0 == "tint").unwrap().2;
        assert_eq!(&buf[tint..tint + 4], &[1.0, 0.0, 0.0, 1.0]);
    }
}
