mode = "dark"

accent = "#a1a1aa"
muted = "#71717a"
background = "#18181b"
foreground = "#f4f4f5"

red = "#e05260"
yellow = "#d4a44c"
orange = "#ce8d55"
green = "#67a87c"
cyan = "#65a5ad"
blue = "#7f9fcb"
magenta = "#a28abe"
bright_red = "#ef6470"
